language: python

matrix:
  include:
    - python: 2.7
      dist: trusty
    - python: 3.4
      dist: trusty
    - python: 3.5
      dist: trusty
    - python: 3.6
      dist: trusty
    - python: 3.7
      dist: xenial
    - python: nightly
      dist: trusty
  allow_failures:
    - python: nightly

install:
  - pip install -r requirements-travis.txt

before_script:
  - flake8
  - ./bin/fetch-configlet
  - ./bin/configlet lint .
  - ./bin/check-readmes.sh

script:
  - ./test/check-exercises.py
