name: "Close stale issues"

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3.0.18
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 21
          days-before-close: 7

          # Milestones on an issue or a PR exempted from being marked as stale.
          exempt-milestones: true
          # Exempt all issues with milestones from being marked as stale.
          exempt-all-issue-milestones: true

          exempt-issue-labels: 'discussion 💬,pinned 📌,enhancement 🦄 ⭐,beginner friendly,maintainer action required❕,on hold ✋🏽'
          stale-issue-label: abandoned 🏚
          stale-issue-message: >
            This issue has been automatically marked as `abandoned 🏚`
            because it has not had recent activity. It will be closed if no
            further activity occurs. Thank you
            for your contributions.
          close-issue-message: >
            Closing stale issue. If this issue is still relevant,
            please reopen it.
          exempt-pr-labels: 'pinned 📌,enhancement 🦄 ⭐,please review 👀,maintainer action required ❕'
          stale-pr-label: abandoned 🏚
          stale-pr-message: >
            This pull request has been automatically marked as `abandoned 🏚`
            because it has not had recent activity. It will be closed if no
            further activity occurs. Thank you for your contributions.
          close-pr-message: >
            Closing stale pull request. If you are still working on this,
            please reopen this pull request.
