name: "Close stale issues"

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 21
          days-before-close: 7

          # Milestones on an issue or a PR exempted from being marked as stale.
          exempt-milestones: true
          # Exempt all issues with milestones from being marked as stale.
          exempt-all-issue-milestones: true

          exempt-issue-labels: "x:action/create,x:action/fix,x:action/improve,x:action/proofread,x:action/sync,
            x:knowledge/none,x:knowledge/elementary,x:knowledge/intermediate,x:knowledge/advanced,x:module/analyzer,
            x:module/concept,x:module/concept-exercise,x:module/generator,x:module/practice-exercise,x:module/representer,
            x:module/test-runner,x:size/massive,x:status/claimed,x:type/ci,x:type/coding,x:type/content,x:type/docker,
            x:type/docs,v3-migration 🤖,bug 🐛,claimed 🐾,discussion 💬,enhancement 🦄 ⭐,first-timers only 🐣
            , good first issue,good first patch,help wanted,improve documentation 💖,improve exercise 💖,
            improve reference docs 💖,improve test case 💖,maintainer action required❕,maintainer chore 🔧,
            new documentation ✨,new exercise ✨,new reference doc ✨,new test case ✨,on hold ✋🏽,pinned 📌"
          stale-issue-label: abandoned 🏚
          stale-issue-message: >
            This issue has been automatically marked as `abandoned 🏚`
            because it has not had recent activity. It will be closed if no
            further activity occurs. Thank you
            for your contributions.
          close-issue-message: >
            Closing stale issue. If this issue is still relevant,
            please reopen it.
          exempt-pr-labels:  "x:action/create,x:action/fix,x:action/improve,x:action/proofread,x:action/sync,
            x:knowledge/none,x:knowledge/elementary,x:knowledge/intermediate,x:knowledge/advanced,x:module/analyzer,
            x:module/concept,x:module/concept-exercise,x:module/generator,x:module/practice-exercise,x:module/representer,
            x:module/test-runner,x:size/massive,x:status/claimed,x:type/ci,x:type/coding,x:type/content,x:type/docker,
            x:type/docs,v3-migration 🤖,bug 🐛,claimed 🐾,discussion 💬,enhancement 🦄 ⭐,first-timers only 🐣
            , good first issue,good first patch,help wanted,improve documentation 💖,improve exercise 💖,
            improve reference docs 💖,improve test case 💖,maintainer action required❕,maintainer chore 🔧,
            new documentation ✨,new exercise ✨,new reference doc ✨,new test case ✨,on hold ✋🏽,pinned 📌"
          stale-pr-label: 'abandoned 🏚'
          stale-pr-message: >
            This pull request has been automatically marked as `abandoned 🏚`
            because it has not had recent activity. It will be closed if no
            further activity occurs. Thank you for your contributions.
          close-pr-message: >
            Closing stale pull request. If you are still working on this,
            please reopen this pull request.
