name: Test Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Run test-runner
        run: docker compose run test-runner
