name: Test Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - name: Run test-runner
        run: docker-compose run test-runner
