name: Test Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run test-runner
        run: docker-compose run test-runner
