name: Test Runner

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-runner:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
      - name: Run test-runner
        run: docker-compose run test-runner
